name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # nome da etapa
        uses: actions/checkout@v3 # action pronta para checkout do código
      
      - name: Set up Node.js # preparando o node
        uses: actions/setup-node@v3 # usando uma action
        with:
          node-version: '22' # especificando a versão
      
      - name: Install dependecies # rodando comando no terminal
        run: npm install
        working-directory: src